#!/bin/bash
#
# /var utilization/monitoring script for pegasus server
# Author: Karthick (karthick.kasithangam@pegs.com)
#
cat /dev/null > /tmp/varstat.out
cat /dev/null > /tmp/output-var
echo "MIME-Version: 1.0
From: Super-User <root@unixmgt01.pegs.com>
To: sysadm@dhisco.com 
Subject: Space of /var on servers running collection script
Content-Type: multipart/mixed
Content-Type: text/html
" >> /tmp/varstat.out
echo "<html>" >> /tmp/varstat.out
echo "<body>" >> /tmp/varstat.out
echo "<div style=\"width: 100%; color: white; background-color: black; border: 2px solid black; padding: 2px;\">" >> /tmp/varstat.out
echo "<p><center><h3><font face=\"Tahoma\">/Var Usage Alert</font></h3></center></p>" >> /tmp/varstat.out
echo "</div>" >> /tmp/varstat.out
echo "<br>" >> /tmp/varstat.out

echo "<table cellspacing=\"8\" style=\"font-family:arial;\">" >> /tmp/varstat.out
echo "<tr>" >> /tmp/varstat.out
echo "<th> Server Name </td>" >> /tmp/varstat.out
echo "<th> Used </td>" >> /tmp/varstat.out
echo "<th> Avail </td>" >> /tmp/varstat.out
echo "<th> USED </td>" >> /tmp/varstat.out
echo "<th> Collect-dir-utilisation </td>" >> /tmp/varstat.out
echo "</tr>" >> /tmp/varstat.out

#for x in `cat /usr/local/sadmutil/collect-server-list`
for x in `cat /usr/local/sadmutil/data/eslservers|grep -v azuldev1|grep -v ussdssas010`
#do
# expr1=`ssh -q $i df -h /var | grep -v Filesystem |  awk 'BEGIN { OFS="\t" ; } { print $3,$4,$5 ; }'`
#ssh -q $i sh /var/tmp/performance-script-housekeeping
#expr2=`ssh -q $i du -sh /var/tmp/collect |awk '{ print $1 }'`
#echo  -e "$i \t $expr1 \t $expr2"
#done >>/tmp/output-var 
#for x in uswuatce01 adsmon uswuatce02 exdcae01 exdcae02 nglqofflnae01 nglqofflnae02
do
ping -c 1 $x > /dev/null 2>&1
if [[ $? -eq 0 ]]; then
expr3=`ssh -q $x df -h /var | grep -v Filesystem |  awk 'BEGIN { OFS="\t" ; } { print $3,$4,$5 ; }'`
chkcond=`echo $expr3|awk '{print $3}'|cut -d '%' -f1`
if [[ $chkcond -ge 85 ]]; then
ssh -q $x sh /var/tmp/performance-script-housekeeping
expr2=`ssh -q $x du -sh /collect |awk '{ print $1 }'`
f1=`echo $expr3|awk '{print $1}'`
f2=`echo $expr3|awk '{print $2}'`
f3=`echo $expr3|awk '{print $3}'`
#echo  -e "$x \t $expr3 \t $expr2"
echo "<tr>" >> /tmp/output-var
echo "<td> $x </td>" >> /tmp/output-var
echo "<td> $f1 </td>" >> /tmp/output-var
echo "<td> $f2 </td>" >> /tmp/output-var
echo "<td bgcolor=\"#FF0000\"> $f3 </td>" >> /tmp/output-var
echo "<td> $expr2 </td>" >> /tmp/output-var
echo "</tr>" >> /tmp/output-var
fi

if [[ $chkcond -ge 75 && $chkcond -lt 85 ]]; then
#ssh -q $x sh /var/tmp/performance-script-housekeeping
expr2=`ssh -q $x du -sh /collect |awk '{ print $1 }'`
f1=`echo $expr3|awk '{print $1}'`
f2=`echo $expr3|awk '{print $2}'`
f3=`echo $expr3|awk '{print $3}'`
#echo  -e "$x \t $expr3 \t $expr2"
echo "<tr>" >> /tmp/output-var
echo "<td> $x </td>" >> /tmp/output-var
echo "<td> $f1 </td>" >> /tmp/output-var
echo "<td> $f2 </td>" >> /tmp/output-var
echo "<td bgcolor=\"#FFFF00\"> $f3 </td>" >> /tmp/output-var
echo "<td> $expr2 </td>" >> /tmp/output-var
echo "</tr>" >> /tmp/output-var
fi

chkcond=0
fi
done
cat /tmp/output-var >> /tmp/varstat.out
echo "</table>" >> /tmp/varstat.out
echo "</body>" >> /tmp/varstat.out
echo "</html>" >> /tmp/varstat.out

cat /tmp/varstat.out |mailx -t
